# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "trackspeedtest"
version = "0.1.0"
authors = ["Giovanni Bassi <giggio@giggio.net>"]
edition = "2018"
# package

[profile.release]
lto = true

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
csv = "1.1.5"
rev_lines = "0.2.1"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
serde_yaml = "0.8.15"
which = "4.0.2"

[dev-dependencies]
pretty_assertions = "0.6.1"
