[package]
name = "speedtest"
version = "0.1.0"
authors = ["Giovanni Bassi <giggio@giggio.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
serde = { version = "1.0.118", features = ["derive"] }
serde_yaml = "0.8.15"
