name: Build giggio/speedtest image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install Rust Stable toolchain
        run: rustup update stable && rustup default stable

      - name: Install Cross
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cross

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u giggio --password-stdin

      - name: Check format
        run: cargo fmt -- --check

      - name: Build arm64
        run: cargo clippy --all-features

      - name: Build arm64
        run: cross build --release --target aarch64-unknown-linux-musl

      - name: Build amd64
        run: cross build --release --target x86_64-unknown-linux-musl

      - name: Build arm32v7
        run: cross build --release --target armv7-unknown-linux-musleabihf

      - name: Test
        run: cross test --target x86_64-unknown-linux-musl

      - name: Release the image
        run: make release_with_docker_only
